name: jaffle_shop
version: '1.0.0'

profile: dbt_learn_snowflake

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

models:
  jaffle_shop:
    marts:
      materialized: table
    staging:
      materialized: view
